# Generated by Django 5.2.17 on 2026-08-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payout_days',
            field=models.CharField(blank=True, default='1', help_text="Для 'weekly': 1 (Пн) - 7 (Вс). Для 'biweekly': числа месяца через запятую (например, 15,30).", max_length=50, verbose_name='Дни выплат'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payout_frequency',
            field=models.CharField(choices=[('weekly', 'Раз в неделю'), ('biweekly', '2 раза в месяц'), ('daily', 'Каждый день'), ('custom', 'По запросу')], default='weekly', max_length=20, verbose_name='График выплат'),
        ),
    ]
