# Generated by Django 5.2.17 on 2026-08-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram'),
        ),
    ]
