# Generated by Django 5.2.17 on 2026-08-10 13:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_payout_days_employee_payout_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay_type',
            field=models.CharField(choices=[('hourly', 'Почасовая ставка'), ('percent', 'Процент от продаж'), ('hybrid', 'Ставка + Процент')], default='hourly', max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Почасовая ставка (₽)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sales_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Процент от продаж (%)'),
        ),
    ]
