# Generated by Django 5.2.17 on 2026-08-16 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_pay_type_alter_employee_hourly_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_all_documents',
            field=models.BooleanField(default=False, help_text='Отметьте, если у сотрудника есть все необходимые документы (паспорт, ИНН, СНИЛС и т.д.)', verbose_name='Все документы в порядке'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_medical_book',
            field=models.BooleanField(default=False, help_text='Отметьте, если у сотрудника есть действующая медицинская книжка', verbose_name='Медицинская книжка'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'is_active'], name='accounts_em_organiz_445f95_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='accounts_em_email_dce3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone'], name='accounts_em_phone_1847a0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['telegram_username'], name='accounts_em_telegra_241e6f_idx'),
        ),
    ]
