# Generated by Django 5.2.17 on 2026-08-12 12:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_pay_type_alter_employee_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='employee_avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.CharField(blank=True, max_length=100, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_med_book',
            field=models.BooleanField(default=False, verbose_name='Наличие медкнижки'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Рейтинг'),
        ),
    ]
