# Generated by Django 5.2.17 on 2026-08-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_avatar_employee_experience_and_more'),
        ('accounts', '0005_employee_has_all_documents_employee_has_medical_book_and_more'),
    ]

    operations = [
    ]
