# Generated by Django 5.2.17 on 2026-08-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260817_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_med_book',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rating',
        ),
    ]
