# Generated by Django 5.2.17 on 2026-08-09 17:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='open', max_length=20, verbose_name='Статус смены')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало смены')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание смены')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка в час (руб.)')),
                ('sales_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент от продаж (%)')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Выручка за смену (руб.)')),
                ('calculated_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итоговый заработок (руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounts.employee', verbose_name='Сотрудник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounts.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ('-opened_at',),
            },
        ),
    ]
