# Generated by Django 5.2.17 on 2026-08-10 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Время начала')),
                ('end_time', models.TimeField(default='21:00', verbose_name='Время окончания')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.employee', verbose_name='Сотрудник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Запланированная смена',
                'verbose_name_plural': 'Запланированные смены',
                'ordering': ('date', 'start_time'),
                'unique_together': {('employee', 'date', 'start_time')},
            },
        ),
    ]
