# Generated by Django 5.2.17 on 2026-08-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shiftschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='schedule_compliance',
            field=models.CharField(choices=[('on_time', 'В срок'), ('late', 'Опоздание'), ('unscheduled', 'Вне графика')], default='on_time', max_length=20, verbose_name='Соблюдение графика'),
        ),
        migrations.AddField(
            model_name='shift',
            name='schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_shifts', to='shifts.shiftschedule', verbose_name='Запланированная смена'),
        ),
    ]
