# Generated by Django 5.2.17 on 2026-08-10 09:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options_alter_organization_options_and_more'),
        ('shifts', '0003_shift_schedule_compliance_shift_schedule_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-opened_at'], 'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AlterModelOptions(
            name='shiftschedule',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Запланированная смена', 'verbose_name_plural': 'Запланированные смены'},
        ),
        migrations.AlterUniqueTogether(
            name='shiftschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shift',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='sales_percentage',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='schedule_compliance',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='schedule_item',
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Подтверждена')], default='approved', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='calculated_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Начисленная выплата (₽)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('completed', 'Завершена')], default='open', max_length=20, verbose_name='Статус смены'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Выручка за смену (₽)'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заметка / Задание'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
