# Generated by Django 5.2.17 on 2026-08-10 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_pay_type_alter_employee_hourly_rate_and_more'),
        ('shifts', '0006_notification_category_notification_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Премия'), ('penalty', 'Штраф')], default='bonus', max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (₽)')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина')),
                ('is_settled', models.BooleanField(default=False, verbose_name='Учтено в выплате')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='accounts.employee', verbose_name='Сотрудник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='accounts.organization', verbose_name='Организация')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='shifts.payrollpayment', verbose_name='Выплата')),
            ],
            options={
                'verbose_name': 'Штраф / Премия',
                'verbose_name_plural': 'Штрафы и Премии',
                'ordering': ['-created_at'],
            },
        ),
    ]
