# Generated by Django 5.2.17 on 2026-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_payrolladjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Отмечается автоматически, когда сотрудник закрывает смену через CRM.', verbose_name='Отработана'),
        ),
    ]
