# Generated by Django 5.2.17 on 2026-08-11 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_pay_type_alter_employee_hourly_rate_and_more'),
        ('shifts', '0008_shiftschedule_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='is_replacement',
            field=models.BooleanField(default=False, verbose_name='Выход на замену'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements_performed', to='accounts.employee', verbose_name='Кем заменён'),
        ),
    ]
