# Generated by Django 5.2.17 on 2026-08-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_pay_type_alter_employee_hourly_rate_and_more'),
        ('shifts', '0009_shiftschedule_is_replacement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('date', models.DateField(verbose_name='Дата')),
                ('color', models.CharField(default='#a6b143', max_length=7, verbose_name='Цвет (HEX)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_notification_sent', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['date'],
            },
        ),
    ]
