# Generated by Django 5.2.17 on 2026-08-12 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_pay_type_alter_employee_hourly_rate_and_more'),
        ('shifts', '0010_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Цвет (HEX)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='target_positions',
            field=models.ManyToManyField(blank=True, related_name='events', to='shifts.position', verbose_name='Для каких должностей (если пусто — для всех)'),
        ),
    ]
