# Generated by Django 5.2.17 on 2026-08-16 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_employee_avatar_remove_employee_experience_and_more'),
        ('shifts', '0011_alter_event_color_alter_event_organization_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'date'], name='shifts_even_organiz_0fd6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', '-created_at'], name='shifts_noti_organiz_ccd2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='shifts_noti_recipie_80e5da_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['organization', '-created_at'], name='shifts_payr_organiz_439792_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['employee', 'is_settled'], name='shifts_payr_employe_94e117_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['organization', '-paid_at'], name='shifts_payr_organiz_326c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['employee', '-paid_at'], name='shifts_payr_employe_21cc85_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['organization', 'name'], name='shifts_posi_organiz_03a01d_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['organization', 'status'], name='shifts_shif_organiz_bcbc05_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['employee', 'status'], name='shifts_shif_employe_3e7030_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['opened_at'], name='shifts_shif_opened__b52e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['is_paid'], name='shifts_shif_is_paid_edb099_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftschedule',
            index=models.Index(fields=['organization', 'date'], name='shifts_shif_organiz_51355f_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftschedule',
            index=models.Index(fields=['employee', 'date'], name='shifts_shif_employe_577cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftschedule',
            index=models.Index(fields=['status'], name='shifts_shif_status_72d59f_idx'),
        ),
    ]
